language: android
jdk: oraclejdk8
sudo: false

android:
  components:
  - platform-tools
  - tools
  - build-tools-28.0.3
  - android-28

script:
    - ./gradlew clean assembleDebug test lint

deploy:
  provider: script
  script: ./gradlew :kotlin-extensions:bintrayUpload
  skip_cleanup: true
  dry-run: false
  on:
    branch: master
