name: "Build & test"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: "Cache Gradle wrapper"
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-wrapper-

      - name: "Cache Gradle dependencies"
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: "Build"
        run: ./gradlew assembleDebug

      - name: "Lint"
        run: ./gradlew lintDebug

      - name: "Unit tests"
        run: ./gradlew testDebug

      - name: "Upload 'extensions' reports"
        uses: actions/upload-artifact@v2
        with:
          name: "extensions-reports"
          path: extensions/build/reports/

      - name: "Upload 'extensions-kotlin' reports"
        uses: actions/upload-artifact@v2
        with:
          name: "extensions-kotlin-reports"
          path: extensions-kotlin/build/reports/